logging:
  level:
    com.mysoft: debug


#本机配置
#file:
#  staticPath: http://localhost:8080/
#  staticPatternPath: /uploadImg/**
#  uploadFolder: D:/MyPicture/

#服务器配置
file:
  staticPath: http://182.61.53.38:8080/
  staticPatternPath: /uploadImg/**
  uploadFolder: /www/myimage/
